### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by m1guelpf** [OrkoHunter/keep#17]
```Proceed to register? [Y/n]: y
Your credentials will be saved in the ~/.keep directory.
Email: soy@miguelpiedrafita.com
Repeat for confirmation: soy@miguelpiedrafita.com
Verifying with existing users...
Traceback (most recent call last):
  File "/usr/local/bin/keep", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keep/commands/cmd_register.py", line 13, in cli
    utils.register()
  File "/usr/local/lib/python2.7/dist-packages/keep/utils.py", line 109, in register
    if r.json()['exists']:
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by OrkoHunter** [comment]
Some error might have occurred with the HTTP requests. Can you try `keep register` again?

**Comment by m1guelpf** [comment]
Every time I do keep init, keep register or sudo keep register, it shows the same...

**Comment by OrkoHunter** [comment]
We don't need sudo anywhere as we do all the things in the .keep directory in our home.

keep init simply creates the .keep directory in home.

Can you show me the contents of .keep by doing
```
l -a ~/.keep
```
And then the contents of the files if any, by `cat` command?

**Comment by OrkoHunter** [comment]
Thanks @m1guelpf for this.
Looking at the error log again, I can see that the error is raised from [this line](https://github.com/OrkoHunter/keep/blob/master/keep/utils.py#L109-L110). A request is sent with a json containing the email id. And it returns a json like this `{'exists': False}` if the user does not exist.
Now, in your case, the request is not in the form of json and hence `r.json()` fails miserably. One way to debug this would be,
Open your python shell in terminal and do
```py
>>> import requests
>>> json_res = {'email': 'soy@miguelpiedrafita.com'}
>>> r = requests.post('https://keep-cli.herokuapp.com/check-user', json=json_res)
>>> print(r.content)

>>> print(r.status_code)
```

This should be interesting as when I tried this, it worked as expected.

**Comment by m1guelpf** [comment]
@OrkoHunter Output:
```py
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> json_res = {'email': 'soy@miguelpiedrafita.com'}
>>> r = requests.post('https://keep-cli.herokuapp.com/check-user', json=json_res)
>>> print(r.content)
{"exists": false}
>>> print(r.status_code)
200
```
