### ISSUE TITLE
Can't Re-Register/Sign-In

### ISSUE THREAD

**Issue by iHarshad** [OrkoHunter/keep#32]
I had to reinstall Yosemite on my MacAir due tosome issues. Before doing the reinstall, I pushed all my **keep** commands to your Heroku server. Now there is no way to Sign-In and pull my commands.

Luckily I have a backup of my `~/.keep` folder from where I can get my commands.

```
Harshad@Harshads-MacBook-Air:~    - - - - - - - - - - - - - - - - - - - - - - -
 ❯  keep init
Initializing environment in ~/.keep directory
...OK
Proceed to register? [Y/n]: Y
Your credentials will be saved in the ~/.keep directory.
Email: haXXXXXXX@gmail.com
Repeat for confirmation: haXXXXXXX@gmail.com
Verifying with existing users...
User already exists !
Email: haXXXXXXX@gmail.com
Repeat for confirmation: haXXXXXXX@gmail.com
Generated password for haXXXXXXX@gmail.com
Registering new user ...

Harshad@Harshads-MacBook-Air:~    - - - - - - - - - - - - - - - - - - - - - - -
 ❯  keep pull
You are not registered.
Proceed to register? [Y/n]: Y
Your credentials will be saved in the ~/.keep directory.
Email: haXXXXXXX@gmail.com
Repeat for confirmation: haXXXXXXX@gmail.com
Verifying with existing users...
User already exists !
Email: haXXXXXXX@gmail.com
Repeat for confirmation: haXXXXXXX@gmail.com
Generated password for haXXXXXXX@gmail.com
Registering new user ...
```
Currently the `~/.keep` folder is empty.

**Comment by OrkoHunter** [comment]
@iHarshad Do you have your original `credentials.json`? If you put that in your `~/.keep` directory, I believe you'll be able to pull the commands. Otherwise, please send me an email on `himanshu.mishra.kgp` and I will send you your `credentials.json`.

PS. I have to rewrite to start using GitHub gists.

**Comment by iHarshad** [comment]
Didn't work.

I put the `.credentials` file in the `~/.keep` folder and issued a `keep pull` command
```
Harshad@Harshads-MacBook-Air:~    - - - - - - - - - - - - - - - - - - - - - - -
 ❯  keep pull
Traceback (most recent call last):
  File "/usr/local/bin/keep", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/keep/commands/cmd_pull.py", line 16, in cli
    utils.pull(ctx, overwrite)
  File "/Library/Python/2.7/site-packages/keep/utils.py", line 97, in pull
    commands.update(my_commands)
TypeError: 'NoneType' object is not iterable
```
I have a backup of my `commands.json` so the data is not lost.

**Comment by paci4416** [comment]
Seems like the code is missing some null checks.
You can place inside the `~/.keep` folder a new `commands.json` file with the string `{}` written in it, pull should work now.

**Comment by iHarshad** [comment]
@paci4416, it worked.
