### ISSUE TITLE
TypeError: string indices must be integers in utils.py

### ISSUE THREAD

**Issue by jrens** [OrkoHunter/keep#49]
> Traceback (most recent call last):
  File "/home/justin/.local/bin/keep", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/justin/.local/lib/python3.6/site-packages/keep/commands/cmd_list.py", line 14, in cli
    utils.list_commands(ctx)
  File "/home/justin/.local/lib/python3.6/site-packages/keep/utils.py", line 72, in list_commands
    table_data.append(['$ ' + cmd, fields['desc'], fields['alias']])
TypeError: string indices must be integers

Entirely suspect user error of some form but I'm not much of a python developer and don't see anything overly wrong there.
Running **keep** works fine.
Above trace was from **keep list**
Reverting back to 2.4.2 works fine other than a nag to update.

**Comment by OrkoHunter** [comment]
This is surely a bug. Can you please provide more info on it?

1. What is the version that caused this error? Is it the latest one on pypi i.e. 2.6.1?
2. Does `~/.keep/commands.json` exist?
3. Can you please share your `~/.keep/commands.json`? (Please hide any sensitive data before posting)

**Comment by jrens** [comment]
1. 2.6.1. Also 2.5.2
2. Exists

[commands.zip](https://github.com/OrkoHunter/keep/files/2781217/commands.zip)

**Comment by OrkoHunter** [comment]
Great! I can now replicate the same error. I will get back once I am able to debug.

**Comment by jrens** [comment]
Thanks for taking care of that. That works
