### ISSUE TITLE
Git push not working

### ISSUE THREAD

**Issue by dna75** [OrkoHunter/keep#53]
When I use the Keep Push command I get the following output;
Traceback (most recent call last):
  File "/usr/bin/keep", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib64/python3.4/site-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/lib/python3.4/site-packages/keep/cli.py", line 59, in get_command
    None, None, ['cli'])
  File "/usr/lib/python3.4/site-packages/keep/commands/cmd_push.py", line 17
    gist_url = f"https://gist.github.com/{token['gist']}"

Commands.json is created on Github but doesn't contain anything.

**Comment by rahuliyer95** [comment]
You need to upgrade your python version. Try using the latest one

**Comment by OrkoHunter** [comment]
Hi @dna75 ! Please use Python 3.6 or later. The error is because of the use of f-strings.

**Comment by dna75** [comment]
Thanks! I forgot to change the version
