### ISSUE TITLE
Not working with command sustition / stored output

### ISSUE THREAD

**Issue by DavidLJz** [OrkoHunter/keep#78]
Hi. This is the command I want to use `cat "$(ls -t | head -1)" | grep ERROR`

Its showing me this error:

```bash
 1       cat "$(ls -t | head -1)" | grep ERROR :: last error log
Traceback (most recent call last):
  File "/usr/local/bin/keep", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keep/commands/cmd_run.py", line 41, in cli
    final_cmd = utils.substitute_pcmd(pcmd, kargs, safe)
  File "/usr/local/lib/python3.6/site-packages/keep/utils.py", line 327, in substitute_pcmd
    return pcmd.substitute(**kargs)
  File "/usr/lib64/python3.6/string.py", line 130, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib64/python3.6/string.py", line 127, in convert
    self._invalid(mo)
  File "/usr/lib64/python3.6/string.py", line 103, in _invalid
    (lineno, colno))
ValueError: Invalid placeholder in string: line 1, col 6

```

**Comment by rahuliyer95** [comment]
Can you please try storing this command instead?

```sh
cat "\$(ls -t | head -1)" | grep ERROR
```

**Comment by DavidLJz** [comment]
> 
> 
> Can you please try storing this command instead?
> 
> ```shell
> cat "\$(ls -t | head -1)" | grep ERROR
> ```

It doesn't appear to be working either

```bash
 1       cat "\$(ls -t | head -1)" | grep ERROR :: last error Log
Traceback (most recent call last):
  File "/usr/local/bin/keep", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keep/commands/cmd_run.py", line 41, in cli
    final_cmd = utils.substitute_pcmd(pcmd, kargs, safe)
  File "/usr/local/lib/python3.6/site-packages/keep/utils.py", line 327, in substitute_pcmd
    return pcmd.substitute(**kargs)
  File "/usr/lib64/python3.6/string.py", line 130, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib64/python3.6/string.py", line 127, in convert
    self._invalid(mo)
  File "/usr/lib64/python3.6/string.py", line 103, in _invalid
    (lineno, colno))
ValueError: Invalid placeholder in string: line 1, col 7

```

**Comment by rahuliyer95** [comment]
Can you please try

```
cat "$$(ls -t | head -1)" | grep ERROR
```

**Comment by rahuliyer95** [comment]
Closed due to inactivity
